

#raw files
data_raw:
    file1: "../data/raw/fra2020-extentofforest.csv"
    file2: "../data/raw/fgoal15.forest_shares.csv"
    file3: "../data/raw/most-visited-countries-2024.csv"
    file4: "../data/raw/WBD_population.csv"

#clean_files

data_clean:
    file1: "../data/clean/NEW_top_visits.csv"
    file2: "../data/clean/w4proj_deforestation.csv"
    file3: "../data/clean/comp_plot_reforest.csv"
    file4: "../data/clean/comp_plot_top_visits.csv"